mappings = {
 'FFA_mass': 'Mass of Fat Free Acid',
 'PIn': 'Protein Intake',
 'BM': 'base bone mass',
 'eps_p': 'deg cost p',
 'Kdnl': 'K DNL',
 'carbfrac': 'frac carbox',
 'BW': 'body weight',
 'Wg': 'Weighting of Oxidation for Glycogenolysis',
 'Wf': 'Weighting of oxidation for lipolysis',
 'Proteol_b': 'Molar Baseline Proteolysis',
 'activ': 'Activity Energy Spent Per Body Weight',
 'hg': 'glycogen hydration coefficient',
 'GNGp': 'gng protein',
 'activ_time': 'activ time',
 'fat_term': 'Fat Term',
 'tef_f': 'tef f',
 'L': 'Lean Tissues',
 'tef_c': 'tef c',
 'tau_therm': 'Delay in Adaptive Thermogenesis',
 'P': 'protein',
 'Lipol_diet': 'effect of carb intake on lipolysis',
 'tef_p': 'tef p',
 'KICW': 'constant intracellular water',
 'Lipol_min': 'Lipol min',
 'BW_ave': 'Baseline Bodyweight',
 'Spi': 'Sensitivity of Oxidation to PI Changes',
 'FIn': 'Fat Intake',
 'GNGp_b': 'base gng p',
 'FIn_b': 'Baseline Fat Intake',
 'carb_term': 'Carb Term',
 'G': 'carb',
 'therm_const': 'Therm const',
 'smr_brain': 'base rmr brain',
 'prot_term': 'Prot Term',
 'GNGf': 'gng fat',
 'rho_f': 'cal dens f',
 'Glycerol_mass': 'Mass of Glycerol',
 'rho_c': 'cal dens c',
 'F_ave': 'Baseline Fat',
 'Glycerol_exog': 'Exog Glycerol Per Kcal Fat Intake',
 'ME_b': 'Baseline Metabolizable Energy Intake',
 'rho_p': 'cal dens p',
 'smr_l': 'Basal RMR of Lean Tissues',
 'activ_tsb': 'Activity Energy Per Body Weight',
 'smr_f': 'base rmr fat',
 'Lipol_b': 'base molar lipolysis',
 'ME': 'Metabolizable Energy Intake',
 'Sci': 'Sensitivity of Oxidation to CI Changes',
 'Mbrain': 'mass brain',
 'hill_dnl': 'Hill DNL',
 'ECW_ave': 'Baseline ECW',
 'activ_vs_rest': 'Thermogenesis Effect on PAE vs RMR',
 'Therm': 'Adaptive Thermogenesis',
 'eta_f': 'dep cost fat',
 'eta_g': 'dep cost c',
 'CIn_b': 'Baseline Carbohydrate Intake',
 'eta_p': 'dep cost p',
 'AA_mass': 'Aminoacid mass',
 'TEE': 'total energy expenditure',
 'TEF': 'thermic effect of food',
 'ECW': 'extracel water',
 'fatfrac': 'frac fatox',
 'K_lip': 'K lip',
 'gngeff': 'efficiency gng',
 'Glycogenol_rate': 'glycogenolysis',
 'protfrac': 'frac protox',
 'CM': 'cell mass',
 'F': 'fat',
 'DNL': 'dnl',
 'hp': 'protein hydration coefficient',
 'Lipol': 'normalized lipolysis rate',
 'Z': 'Z',
 'smr_lb': 'Baseline Basal RMR of Lean Tissues',
 'Lipol_max': 'Lipol max',
 'Glycogenol': 'Normalized Glycogenolysis',
 'G_ave': 'base carb',
 'Wci': 'Weighting of Oxidation for Basal CI',
 'PIn_b': 'Baseline Protein Intake',
 'Ec': 'Ec',
 'Denom': '1',
 'dPIn': 'Change in Protein Intake',
 'Lipol_rate': 'lipolysis',
 'Proteol_rate': 'proteolysis',
 'CIn': 'Carbohydrate Intake',
 'L_ave': 'Baseline Lean Mass',
 'PfracCM': 'Protein Fraction of Cell Mass',
 'Wpi': 'Weighting of Oxidation for Basal PI',
 'P_ave': 'Baseline Protein',
 'GNGf_Endog': 'GNG Fat Endog',
 'dnleff': 'efficiency dnl',
 'GNGf_bEndog': 'Baseline GNG Fat Endog',
 'activ_b': 'Baseline Activity Energy Per Body Weight',
 'Proteol': 'Normalized Proteolysis',
 'ICS': 'intracel solids',
 'TG_mass': 'mass tg',
 'GNGf_Exog': 'GNG Fat Exog'
}

constants = {
	'cal dens p': '4.7',
	'Molar Baseline Proteolysis': '2.73',
	'Basal RMR of Lean Tissues': '0.0239374',
	'base rmr fat': '0.0045',
	'base rmr brain': '0.0239374',
	'Aminoacid mass': '110',
	'Baseline Fat Intake': '1332.52',
	'mass brain': '1400',
	'deg cost p': '0.172727',
	'dep cost fat': '0.176744',
	'dep cost c': '0.211111',
	'dep cost p': '0.863636',
	'efficiency gng': '0.8',
	'efficiency dnl': '0.8',
	'Baseline Protein Intake': '457.38',
	'Baseline Carbohydrate Intake': '1811.51',
	'cal dens c': '4.18',
	'cal dens f': '9.44',
	'Mass of Glycerol': '92',
	'mass tg': '860',
	'tef p': '0.25',
	'tef c': '0.075',
	'tef f': '0.025',
	'Weighting of Oxidation for Glycogenolysis': '1.74429',
	'Weighting of Oxidation for Basal CI': '3.31414',
	'Sensitivity of Oxidation to CI Changes': '0.761188',
	'Weighting of oxidation for lipolysis': '4.23519',
	'Sensitivity of Oxidation to PI Changes': '15.0253',
	'Weighting of Oxidation for Basal PI': '0.1',
	'Baseline Activity Energy Per Body Weight': '0.0256755',
	'Thermogenesis Effect on PAE vs RMR': '0.52',
	'Delay in Adaptive Thermogenesis': '7',
	'Therm const': '0.8',
	'base molar lipolysis': '0.16',
	'Lipol max': '3.1',
	'Lipol min': '0.9',
	'base gng p': '100',
	'Hill DNL': '4',
	'K DNL': '2',
	'glycogen hydration coefficient': '2.7',
	'protein hydration coefficient': '2',
	'constant intracellular water': '12051.9',
	'intracel solids': '3967.28',
	'Baseline Bodyweight': '67533',
	'Baseline Fat': '9050',
	'base carb': '500',
	'Protein Fraction of Cell Mass': '0.2'
}