cal_dens_p = 4.7
Molar_Baseline_Proteolysis = 2.73
Basal_RMR_of_Lean_Tissues = 0.0239374
base_rmr_fat = 0.0045
base_rmr_brain = 0.0239374
Aminoacid_mass = 110.0
Baseline_Fat_Intake = 1332.52
mass_brain = 1400.0
deg_cost_p = 0.172727
dep_cost_fat = 0.176744
dep_cost_c = 0.211111
dep_cost_p = 0.863636
efficiency_gng = 0.8
efficiency_dnl = 0.8
Baseline_Protein_Intake = 457.38
Baseline_Carbohydrate_Intake = 1811.51
cal_dens_c = 4.18
cal_dens_f = 9.44
Mass_of_Glycerol = 92.0
mass_tg = 860.0
tef_p = 0.25
tef_c = 0.075
tef_f = 0.025
Weighting_of_Oxidation_for_Glycogenolysis = 1.74429
Weighting_of_Oxidation_for_Basal_CI = 3.31414
Sensitivity_of_Oxidation_to_CI_Changes = 0.761188
Weighting_of_oxidation_for_lipolysis = 4.23519
Sensitivity_of_Oxidation_to_PI_Changes = 15.0253
Weighting_of_Oxidation_for_Basal_PI = 0.1
Baseline_Activity_Energy_Per_Body_Weight = 0.0256755
Thermogenesis_Effect_on_PAE_vs_RMR = 0.52
Delay_in_Adaptive_Thermogenesis = 7.0
Therm_const = 0.8
base_molar_lipolysis = 0.16
Lipol_max = 3.1
Lipol_min = 0.9
base_gng_p = 100.0
Hill_DNL = 4.0
K_DNL = 2.0
glycogen_hydration_coefficient = 2.7
protein_hydration_coefficient = 2.0
constant_intracellular_water = 12051.9
intracel_solids = 3967.28
Baseline_Bodyweight = 67533.0
Baseline_Fat = 9050.0
base_carb = 500.0
Protein_Fraction_of_Cell_Mass = 0.2

BWinit = 67533.0
Finit = 9050.0

base_bone_mass = 0.04 * Baseline_Bodyweight
Baseline_ECW = 0.7 * 0.235 * Baseline_Bodyweight
Baseline_Lean_Mass = Baseline_Bodyweight - Baseline_Fat
Baseline_Protein = Protein_Fraction_of_Cell_Mass * ( Baseline_Lean_Mass - base_bone_mass - Baseline_ECW)
Exog_Glycerol_Per_Kcal_Fat_Intake=Mass_of_Glycerol / ( cal_dens_f * mass_tg )
Baseline_GNG_Fat_Endog = base_molar_lipolysis * Mass_of_Glycerol * cal_dens_c
Baseline_Metabolizable_Energy_Intake = Baseline_Carbohydrate_Intake + Baseline_Fat_Intake +Baseline_Protein_Intake
Baseline_Basal_RMR_of_Lean_Tissues = 0.0239374

TEFinit = tef_f * Baseline_Fat_Intake + tef_c * Baseline_Carbohydrate_Intake + tef_p * Baseline_Protein_Intake
extraFinit = 0.0	
Linit = BWinit - Finit
ECW_b = 0.7*0.235*Baseline_Bodyweight	
CMinit = (Linit - base_bone_mass - ECW_b)
Pinit = Protein_Fraction_of_Cell_Mass*(Linit - base_bone_mass - ECW_b)
Proteol_init = Molar_Baseline_Proteolysis*(Pinit/Baseline_Protein)
GNGp_init = base_gng_p*(Proteol_init/Molar_Baseline_Proteolysis)
Sl = 2.0/3.0
Lipol_init = base_molar_lipolysis*(Finit/Baseline_Fat)**Sl
GNGf_bExog = Exog_Glycerol_Per_Kcal_Fat_Intake*Baseline_Fat_Intake*cal_dens_c
GNGf_init = Baseline_GNG_Fat_Endog*(Lipol_init/base_molar_lipolysis) + GNGf_bExog
Ginit =500.0
DNL_init = Baseline_Carbohydrate_Intake * (Ginit/base_carb)**Hill_DNL/(K_DNL**Hill_DNL + (Ginit/base_carb)**Hill_DNL)
ATP_P_proteol = 1.0	
ATP_kcal = 19.0		
Glycogenol_b = 1.0	
Glycogenol_init = Glycogenol_b*(Ginit/base_carb)
G_mass = 180.0	
Ec = Baseline_Metabolizable_Energy_Intake - (TEFinit + Baseline_Activity_Energy_Per_Body_Weight * BWinit + Baseline_Basal_RMR_of_Lean_Tissues*(CMinit-mass_brain) + base_rmr_brain*mass_brain + base_rmr_fat * Finit + (1.0-efficiency_gng)*(GNGp_init+GNGf_init)+(1.0-efficiency_dnl)*DNL_init+ (dep_cost_p + ATP_P_proteol*ATP_kcal/Aminoacid_mass)*Proteol_init*Aminoacid_mass + dep_cost_fat*Lipol_init*mass_tg+ dep_cost_c *Glycogenol_init*G_mass)

def Ecval():
	return Ec